version: "3.9"

networks:
  tomaramos-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/16
          gateway: 10.12.0.1

services:
  # ---------------------- NGINX ---------------------- #
  tomaramos-nginx:
    container_name: tomaramos-nginx-container
    build:
      context: NGINX
      args:
        NGINX_VERSION: 1.22.1
        WEB_APP_PORT: ${WEB_SERVER_PORT}
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      tomaramos-net:
    restart: "always"
    depends_on:
      - tomaramos-rails

  # ---------------------- DBMS ---------------------- #
  tomaramos-postgres:
    container_name: tomaramos-postgres-container
    build:
      context: PostgresDB
      args:
        UBUNTU_VERSION: 22.04
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_LOG_LEVEL: ${POSTGRES_LOG_LEVEL}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      tomaramos-net:
    restart: "unless-stopped" # <- so that `docker-compose stop` for this won't destroy the database
    volumes:
      - "./postgres-volume:/var/lib/postgresql/${POSTGRES_VERSION}/main:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 5s
      retries: 1
      start_period: 20s

  # ---------------------- Rails web app ---------------------- #
  tomaramos-rails:
    container_name: tomaramos-rails-container
    build:
      context: TomaRamosWebApp
      args:
        RUBY_VERSION: 3.1.1
        WEB_SERVER_PORT: ${WEB_SERVER_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: "tomaramos-postgres"
      ADMIN_USER_PASSWORD: "qwerty"
      WEB_SERVER_PORT: ${WEB_SERVER_PORT}
      SERVE_OVER_HTTPS: ${SERVE_OVER_HTTPS}
      HTML_TO_IMG_PORT: ${HTML_TO_IMG_PORT}
    networks:
      tomaramos-net:
    #ports:
      #- "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    depends_on:
      tomaramos-postgres:
        condition: service_healthy
    restart: "no"

  # ---------------------- HTML to Image microservice ---------------------- #
  html-to-image:
    container_name: html-to-image-container
    build:
      context: HTMLToImage
      args:
        PYTHON_VERSION: "3.10"
        API_PORT: ${HTML_TO_IMG_PORT}
    networks:
      tomaramos-net:
