version: "3.9"

networks:
  tomaramos-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/16
          gateway: 10.12.0.1

services:
  # ---------------------- DBMS ---------------------- #
  postgres:
    container_name: "tomaramos-postgres"
    build:
      context: PostgresDB
      args:
        UBUNTU_VERSION: "22.04"
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_LOG_LEVEL: ${POSTGRES_LOG_LEVEL}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      tomaramos-net:
    restart: "unless-stopped"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - "./postgres-volume:/var/lib/postgresql/${POSTGRES_VERSION}/main:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT}"]
      interval: 20s
      timeout: 5s
      retries: 1
      start_period: 20s

  # ---------------------- Rails web app ---------------------- #
  rails:
    container_name: "tomaramos-rails"
    build:
      context: TomaRamosWebApp
      args:
        RUBY_VERSION: 3.1.1
        WEB_SERVER_PORT: ${WEB_SERVER_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: "tomaramos-postgres"
      ADMIN_USER_PASSWORD: "qwerty"
      WEB_SERVER_PORT: ${WEB_SERVER_PORT}
      HTML_TO_IMG_PORT: ${HTML_TO_IMG_PORT}
    networks:
      tomaramos-net:
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    volumes:
      - ".env:/home/tomaramos/.env:ro"
      # - ".secrets.env:/home/tomaramos/.secrets.env:ro" #! unused
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${WEB_SERVER_PORT}/healthcheck || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 20s

  # ---------------------- HTML to Image microservice ---------------------- #
  html-to-image:
    container_name: "tomaramos-html-to-image"
    build:
      context: HTMLToImage
      args:
        PYTHON_VERSION: "3.10"
        API_PORT: ${HTML_TO_IMG_PORT}
    networks:
      tomaramos-net:
    ports:
      - "${HTML_TO_IMG_PORT}:${HTML_TO_IMG_PORT}"
    restart: "on-failure"
