version: "3.9"

networks:
  ifgarces-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/16
          gateway: 10.12.0.1

services:
  # ---------------------- DBMS ---------------------- #
  tomaramos-postgres:
    container_name: tomaramos-postgres-container
    build:
      context: PostgresDB
      args:
        UBUNTU_VERSION: 22.04
    environment:
      POSTGRES_LOG_LEVEL: ${POSTGRES_LOG_LEVEL}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      ifgarces-net:
        ipv4_address: 10.12.0.2
    restart: "unless-stopped" # <- so that `docker-compose stop` for this won't destroy the database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 5s
      retries: 2
      start_period: 20s

  # ---------------------- Rails web app ---------------------- #
  tomaramos-rails:
    container_name: tomaramos-rails-container
    build:
      context: TomaRamosWebApp
      args:
        RUBY_VERSION: 3.1.1
        WEB_SERVER_PORT: ${WEB_SERVER_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      ADMIN_USER_PASSWORD: "qwerty"
      WEB_SERVER_PORT: ${WEB_SERVER_PORT}
      WEB_SERVER_HOST: ${WEB_SERVER_HOST}
      SERVE_OVER_HTTPS: ${SERVE_OVER_HTTPS}
      HTML_TO_IMG_PORT: ${HTML_TO_IMG_PORT}
    networks:
      ifgarces-net:
        ipv4_address: 10.12.0.3
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    depends_on:
      tomaramos-postgres:
        condition: service_healthy
    restart: "no"

  # ---------------------- HTML to Image microservice ---------------------- #
  html-to-image:
    container_name: html-to-image-container
    build:
      context: HTMLToImage
      args:
        PYTHON_VERSION: "3.10"
        API_PORT: ${HTML_TO_IMG_PORT}
    networks:
      ifgarces-net:
        ipv4_address: 10.12.0.4
    ports:
      - "${HTML_TO_IMG_PORT}:${HTML_TO_IMG_PORT}"
