# --------------------------------------------------------------------------------------------------
# Database connection settings. Note that there is embedded Ruby code here, which is correctly
# supported by Rails. You can "test" this file with the command `erb config/database.yml` and
# check the parsed output. Also, note that this file reads the ENV variables set at both .env files
# at the root directory of the project. Will fork properly for both virtualized and native cases.
# --------------------------------------------------------------------------------------------------

<%
require "dotenv"
Dotenv.load(File.join("..", ".env"), File.join("..", ".secrets.env"))
%>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>
  username: "tomaramosuandes"
  password: "tomaramosuandes"

development:
  <<: *default
  password: "tomaramosuandes"
  database: tomaramosuandes_development
  min_messages: notice

test:
  <<: *default
  database: tomaramosuandes_test
  min_messages: log

production:
  # WIP
  <<: *default
  password: <%= ENV.fetch("TOMARAMOSUANDES_DATABASE_PASSWORD") { "todo" } %>
  database: tomaramosuandes_production
  min_messages: warning
